Bump Webmock to remove API error
- Bumping to Ruby 2.5.3 and running specs generated:
  NoMethodError: undefined method `close' for #<StubSocket:0x007f871cf99070>
  Did you mean?  closed?
                 clone

  This turned ut to be Webmock, that had to be bumped > 2.3.2
  see: https://github.com/bblimke/webmock/issues/683